/*
 * model.js
 * --------
 * Loads the trained model weights (model_weights.js, generated by
 * python/train_model.py) and defines how the model is applied to a
 * feature vector. Both classifiers are linear, so "running the model"
 * is just a dot product:
 *   score = w . feature + b
 *   Logistic Regression : P(neutron) = sigmoid(score)  -> Neutron if >= 0.5
 *   Linear SVM            : decision  = score            -> Neutron if >= 0
 *
 * Requires model_weights.js to be loaded first (defines MODEL_WEIGHTS).
 */

function predictLive(feature){
  let zLR = MODEL_WEIGHTS.lr.b, zSVM = MODEL_WEIGHTS.svm.b;
  for (let i=0;i<512;i++){ zLR += MODEL_WEIGHTS.lr.w[i]*feature[i]; zSVM += MODEL_WEIGHTS.svm.w[i]*feature[i]; }
  const pLR = 1/(1+Math.exp(-zLR));
  return {
    lrPred: pLR >= 0.5 ? 1 : 0, lrProba: pLR,
    svmPred: zSVM >= 0 ? 1 : 0, svmScore: zSVM,
  };
}

